Traceback (most recent call last):
  File "/v/filer4b/v38q001/nathesh/Documents/Research/main.py", line 3, in <module>
    from sklearn.datasets import fetch_20newsgroups as ngs
  File "/u/nathesh/.local/lib/python2.7/site-packages/sklearn/datasets/__init__.py", line 7, in <module>
    from .base import load_diabetes
  File "/u/nathesh/.local/lib/python2.7/site-packages/sklearn/datasets/base.py", line 25, in <module>
    from ..utils import check_random_state
  File "/u/nathesh/.local/lib/python2.7/site-packages/sklearn/utils/__init__.py", line 10, in <module>
    from .murmurhash import murmurhash3_32
  File "numpy.pxd", line 155, in init sklearn.utils.murmurhash (sklearn/utils/murmurhash.c:5029)
ValueError: numpy.dtype has the wrong size, try recompiling
